

ota:
  password: "90dc1eb8df95f5e147d6495b70b5f56d"
  platform: esphome

esp8266:
  board: d1_mini

network:
  enable_ipv6: True

# ---
substitutions:
  room: og2flur
  uroom: "2OG-Flur"

esphome:
  name: $room-sensor
  area: Treppenhaus
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led
      

mqtt:
  broker: mqtt.ch5.garf.de
  discovery: false
  discovery_retain: false
  topic_prefix: Chattenweg5/$uroom/sensor
  reboot_timeout: 0s
  keepalive: 20s
  username: $room-sensor
  password: $room-sensor

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: bus_a
    scan: true
    sda: 4
    scl: 5
    frequency: 400kHz


sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    address: 0x39
    update_interval: 60s
    accuracy_decimals: 2
  - platform: htu21d
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -2
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
#    address: 0x76
    update_interval: 5s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  
binary_sensor:
  - platform: homeassistant
    entity_id: input_boolean.alarmierung
    id: alarmierung
    internal: true
  - platform: gpio
    pin: 12
    id: ${room}_motion
    name: "${uroom} Motion"
    device_class: motion
    filters:
      - delayed_off: 60s
    on_press:
      then:
        - if:
            condition: 
              binary_sensor.is_on: alarmierung
            then:
              - light.turn_on: 
                  id: led
                  brightness: 100%
                  red: 100%
                  green: 0
                  blue: 0
    on_release:
      then:
        - light.turn_off: led

light:
  - platform: neopixelbus
    id: led
    variant: WS2811
    type: GRB
    pin: 14
    num_leds: 1
    name: "${uroom} LED"

text_sensor:
  - platform: wifi_info
    ip_address: 
      name: IP address
      address_0:
        name: IP address 0
      address_1:
        name: IP address 1
      address_2:
        name: IP address 2
      address_3:
        name: IP address 3
      address_4:
        name: IP address 4
    dns_address: 
      name: DNS address
    mac_address: 
      name: MAC address
