

ota:
  password: "90dc1eb8df95f5e147d6495b70b5f56d"

esp8266:
  board: d1_mini


# ---
substitutions:
  room: og2flur
  uroom: "2OG-Flur"

esphome:
  name: $room-sensor
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led
      



# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

i2c:
  - id: bus_a
    scan: true
    sda: 4
    scl: 5
    frequency: 400kHz


sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    address: 0x39
    update_interval: 60s
    accuracy_decimals: 2
  - platform: htu21d
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -2
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
#    address: 0x76
    update_interval: 5s

binary_sensor:
  - platform: gpio
    pin: 12
    id: ${room}_motion
    name: "${uroom} Motion"
    device_class: motion
    on_press:
      then:
        - light.turn_on: 
            id: led
            brightness: 100%
            red: 0
            green: 0
            blue: 100%
    on_release:
      then:
        - light.turn_off: led

light:
  - platform: neopixelbus
    id: led
    variant: WS2811
    type: GRB
    pin: 14
    num_leds: 1
    name: "${uroom} LED"

