esphome:
  name: 3d-drucker-beleuchtung
#  platformio_options:
#    build_flags:
#      - -DPIO_FRAMEWORK_ARDUINO_LWIP2_IPV6_LOW_MEMORY


esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "0a54f8ba6e6d2af06170ce2c25167629"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


wled:
   
sensor:
  - platform: hx711
    name: "Gewicht Filamentspule"
    dout_pin: 13
    clk_pin: 12

light:
  - platform: neopixelbus
    type: GRBW
    id: led
    variant: 800KBPS
    pin: 14
    num_leds: 24
    name: "LED"
    effects:
      - wled:


