substitutions:
  room: arbeitszimmer
  uroom: Arbeitszimmer


esphome:
  name: $room-sensor
  area: Arbeitszimmer
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
  on_boot:
#    - priority: 250
#      then:
#        - delay: 15s
#        - lambda: |-
#            id(ble_tracker).set_scan_continuous(true);
#            id(ble_tracker).start_scan();
    - priority: 600
      then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led

 
esp32:
  board: lolin_c3_mini # c3 pico
  framework:
    type: arduino

# Ports used
# Right row: 
#  TX
#  RX
#  10 SCL
#   8 SDA
#   7 (LED)
#   6
#   GND
#   5V
# Left row
#  EN
#   3
#   2
#   1
#   0
#   4 uart rx
#   5 uart tx
#  3.3v


network:
  enable_ipv6: true

#esp32_ble_tracker:
#  id: ble_tracker
#  scan_parameters:
#    continuous: false
#    interval: 211ms
#    window: 120ms
#    active: true

#bluetooth_proxy:
#  active: true

# Enable Home Assistant API
api:
  encryption:
    key: "RhqBxxEgN+A2oPYWWv7vZAvjHgMINwam9YZePtojI0s="

ota:
  password: "f3269d23a656daab91ce786e042593ab"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5

mqtt:
  broker: mqtt.ch5.garf.de
  discovery: false
  discovery_retain: false
  topic_prefix: /Chattenweg5/$uroom/sensor
  reboot_timeout: 0s
  keepalive: 20s
  username: $room-sensor
  password: $room-sensor

# Enable logging
logger:
  level: DEBUG

debug: 
  update_interval: 120s

light:
  - platform: neopixelbus
    pin: GPIO7
    variant: ws2811
    num_leds: 1
    name: LED
    type: RGB
    id: led
 

i2c:
  - id: bus_a
    scan: True
    sda: GPIO8
    scl: GPIO10
    frequency: 10khz

uart:
  rx_pin: GPIO4
  tx_pin: GPIO5
  baud_rate: 115200
  id: uartpresence

ld2420:

select:
  - platform: ld2420
    operating_mode:
      name: Operating Mode

number:
  - platform: ld2420
    presence_timeout:
      name: Detection Presence Timeout
    min_gate_distance:
      name: Detection Gate Minimum
    max_gate_distance:
      name: Detection Gate Maximum

    gate_select:
      name: Select Gate to Set
    still_threshold:
      name: Set Still Threshold Value
    move_threshold:
      name: Set Move Threshold Value

    gate_move_sensitivity:
      name: Move Calibration Sensitivity Factor
    gate_still_sensitivity:
      name: Still Calibration Sensitivity Factor

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address
  - platform: ld2420
    fw_version:
      name: LD2420 Firmware


button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"
  - platform: ld2420
    apply_config:
      name: Apply Config
    factory_reset:
      name: Factory Reset
    restart_module:
      name: Restart Module
    revert_config:
      name: Undo Edits

sensor:
  - platform: ld2420
    moving_distance:
      name : Moving Distance
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: sps30
    pm_1_0:
      name: "${uroom} PM <1µm Weight concentration"
    pm_2_5:
      name: "${uroom} PM <2.5µm Weight concentration"
    pm_4_0:
      name: "${uroom} PM <4µm Weight concentration"
    pm_10_0:
      name: "${uroom} PM <10µm Weight concentration"
    pmc_0_5:
      name: "${uroom} PM <0.5µm Number concentration"
    pmc_1_0:
      name: "${uroom} PM <1µm Number concentration"
    pmc_2_5:
      name: "${uroom} PM <2.5µm Number concentration"
    pmc_4_0:
      name: "${uroom} PM <4µm Number concentration"
    pmc_10_0:
      name: "${uroom} PM <10µm Number concentration"
    pm_size:
      name: "${uroom} Typical Particle size"
  - platform: sgp30
    update_interval: 1s
    store_baseline: yes
    eco2:
      name: "${uroom} CO2"
      id: ${room}_co2
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/${uroom}/CO2"
              payload: !lambda |-
                return to_string(id(${room}_co2).state);
    tvoc:
      name: "${uroom} TVOC"
      filters:
        - sliding_window_moving_average:
            window_size: 60
            send_every: 60
    compensation:
      temperature_source: ${room}_temperature
      humidity_source: ${room}_humidity
    baseline:
      eco2_baseline: 41270
      tvoc_baseline: 40117
    eco2_baseline:
      name: "${uroom} ECO2 Baseline"
    tvoc_baseline:
      name: "${uroom} TVOC Baseline"
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: bme680
    address: 0x77
    temperature:
      accuracy_decimals: 2
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      filters:
        - offset: -3
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/$uroom/temperature"
              payload: !lambda |-
                return to_string(id(${room}_temperature).state);
    pressure:
      accuracy_decimals: 2
      name: "${uroom} Luftdruck"
      id: ${room}_pressure
    humidity:
      accuracy_decimals: 2
      name: "${uroom} Luftfeuchtigkeit"
      id: ${room}_humidity
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/$uroom/humidity"
              payload: !lambda |-
                return to_string(id(${room}_humidity).state);
    gas_resistance:
      accuracy_decimals: 2
      name: "${uroom} Gas Resistance"
      id: ${room}_gasresistance
  - platform: max44009
    name: "${uroom} Helligkeit"
    id: ${room}_light
    accuracy_decimals: 2
    update_interval: 60s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
    id: ${room}_abshumidity
  - platform: template
    name: "${uroom} IAQ"
    id: ${room}_iaq
    unit_of_measurement: IAQ
    lambda: 'return log(id(${room}_gasresistance).state) + 0.04 * id(${room}_humidity).state;' 

binary_sensor:
  - platform: ld2420
    has_target:
      name: Presence
      filters:
        delayed_off: 60s
