esphome:
  name: egflur-sensor

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "17cdc84dc07200c621bf878a2df9b871"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Egflur-Sensor Fallback Hotspot"
    password: "C3KnVzLtcZoh"

captive_portal:
