substitutions:
  room: egflurcam
  uroom: "Erdgeschoss Flur Camera"

esphome:
  name: ${room}

esp32:
  board: m5stack-timer-cam

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "3d01a0bb3c2db3f521c6d0c493ba1773"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: "${uroom} Safe Mode"

esp32_camera:
  name: "${uroom} Camera"
  external_clock:
    pin: GPIO27
    frequency: 20MHz
  i2c_pins:
    sda: GPIO25
    scl: GPIO23
  data_pins: [GPIO17, GPIO35, GPIO34, GPIO5, GPIO39, GPIO18, GPIO36, GPIO19]
  vsync_pin: GPIO22
  href_pin: GPIO26
  pixel_clock_pin: GPIO21
  reset_pin: GPIO15
  resolution: 800x600

esp32_camera_web_server:
  - port: 8080
    mode: stream
  - port: 8081
    mode: snapshot

sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s

binary_sensor:
  - platform: homeassistant
    entity_id: input_boolean.alarmierung
    id: alarmierung
    internal: true
