esphome:
  name: esp-ipv6-test

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    version: latest
    sdkconfig_options:
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y


network:
  enable_ipv6: true

# Enable logging
logger:
  level: INFO

# Enable Home Assistant API
api:
  encryption:
    key: "ASubiRsXrBBWf2bJp+k+IN4xdrfkJPDcquwnXSI3nrQ="

ota:
  password: "6c32b624b210a2182dddfede9bcf2b59"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


  
  
