substitutions:
  room: esp-ipv6-test
  uroom: ESP-IPv6-Test

esphome:
  name: ${room}
  friendly_name: ${uroom}
#  platformio_options:
#    board_build.extra_flags:
#      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
  
esp32:
  board: esp32-s3-devkitc-1
  variant: ESP32S3
  framework:
    type: esp-idf
    


network:
  enable_ipv6: true
  min_ipv6_addr_count: 2

# Enable logging
logger:
  level: VERBOSE

debug:

# Enable Home Assistant API
api:
  encryption:
    key: "ASubiRsXrBBWf2bJp+k+IN4xdrfkJPDcquwnXSI3nrQ="

ota:
  password: "6c32b624b210a2182dddfede9bcf2b59"

wifi:
  ssid: !secret guest_ssid
  password: !secret guest_password
  output_power: 8.5
  fast_connect: true
  use_address: fdd1:9494:7978:0016:de54:75ff:fee1:b8cc

# i2c:
#  sda: GPIO33
#  scl: GPIO35


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: wifi_signal
    name: "$uroom WiFi Signal Sensor"

      
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      address_0:
        name: ESP IP Address 0
      address_1:
        name: ESP IP Address 1
      address_2:
        name: ESP IP Address 2
      address_3:
        name: ESP IP Address 3
      address_4:
        name: ESP IP Address 4
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address