substitutions:
  room: esp-ipv6-test
  uroom: ESP-IPv6-Test

esphome:
  name: ${room}
  friendly_name: ${uroom}
#  platformio_options:
#    board_build.extra_flags:
#      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
  
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino


network:
  enable_ipv6: true

# Enable logging
logger:
  level: VERBOSE

debug:

# Enable Home Assistant API
api:
  encryption:
    key: "ASubiRsXrBBWf2bJp+k+IN4xdrfkJPDcquwnXSI3nrQ="

ota:
  password: "6c32b624b210a2182dddfede9bcf2b59"

wifi:
  ssid: !secret guest_ssid
  password: !secret guest_password
  output_power: 8.5
  fast_connect: true

# i2c:
#  sda: GPIO33
#  scl: GPIO35


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: internal_temperature
    name: "${uroom} CPU Temperatur"
  - platform: wifi_signal
    name: "$uroom WiFi Signal Sensor"

      
text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results
    dns_address:
      name: ESP DNS Address