substitutions:
  room: esp-ipv6-test
  uroom: ESP-IPv6-Test

esphome:
  name: ${room}
  friendly_name: ${uroom}
  platformio_options:
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"  # Override, defaults to '-DARDUINO_USB_CDC_ON_BOOT=1'
  
esp32:
  # board: wemos_d1_mini32
  board: lolin_s3
  # framework:
  #  type: arduino
  #  version: latest


network:
#  enable_ipv6: true

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "ASubiRsXrBBWf2bJp+k+IN4xdrfkJPDcquwnXSI3nrQ="

ota:
  password: "6c32b624b210a2182dddfede9bcf2b59"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# i2c:
#  sda: GPIO33
#  scl: GPIO35

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO33
  rx_pin: GPIO37

ld2410:
  timeout: 150s
  max_move_distance : 6m
  max_still_distance: 0.75m
  g0_move_threshold: 50
  g1_move_threshold: 50
  g2_move_threshold: 40
  g3_move_threshold: 40
  g4_move_threshold: 40
  g5_move_threshold: 40
  g6_move_threshold: 30
  g7_move_threshold: 30
  g8_move_threshold: 30
  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 40
  g3_still_threshold: 40
  g4_still_threshold: 40
  g5_still_threshold: 40
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

sensor:
  - platform: internal_temperature
    name: "${uroom} CPU Temperatur"
  - platform: wifi_signal
    name: "$uroom WiFi Signal Sensor"
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
  - platform: internal_temperature
    name: "${uroom} CPU Temperatur"
      
binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
