esphome:
  name: esp32-c6-firebeetle
  friendly_name: esp32-c6-firebeetle
  on_boot:
    - priority: 100
      then:
        - light.turn_on: statusled

  on_shutdown:
    - priority: 600
      then:
        - light.turn_off: statusled  
 

external_components:
  - source: github://pr#9021
    components: [adc]

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "IyT8zQwmTGhLxHjIS9Om7tvxlIjlqo07Mgcbq0isYiU="

ota:
  - platform: esphome
    password: "1de71de3ffebf50ae3bd93fe1109b622"

deep_sleep:
  run_duration: 65s
  sleep_duration: 5min
  id: sleeper

# Enable logging
logger:
  level: VERBOSE
  

network:
  enable_ipv6: True

openthread:
  tlv: !secret openthread 

globals:
  id: readyforsleep
  type: int
  restore_value: False
  initial_value: '0' 

                        

i2c:
  scl: GPIO20
  sda: GPIO19
  #scan: True
  #frequency: 100kHz
    
  
#bme68x_bsec2_i2c:
#  model: bme680
#  address: 0x77
#  sample_rate: LP
  
switch:
  - platform: homeassistant
    entity_id: input_boolean.sensor_vorgarten_preventsleep
    id: preventsleep
    internal: True
    restore_mode: ALWAYS_OFF
    on_turn_on: 
      then:
        - deep_sleep.prevent: sleeper
    on_turn_off: 
      then:
        - deep_sleep.allow: sleeper

text_sensor:
  #- platform: bme68x_bsec2
  #  iaq_accuracy: 
  #    name: "IAQ Accuracy"
  - platform: version
    name: "Esphome Version"
  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "d"
      hours: "h"
      minutes: "m"
  - platform: openthread_info
    ip_address:
      name: "Off-mesh routable IP Address"
    channel:
      name: "Channel"
    role:
      name: "Device Role"
      id: role
    rloc16:
      name: "RLOC16"
    ext_addr:
      name: "Extended Address"
    eui64:
      name: "EUI64 Interface ID"
    network_name:
      name: "Network Name"
    network_key:
      name: "Network Key"
    pan_id:
      name: "PAN ID"
    ext_pan_id:
      name: "Extended PAN ID"


sensor:
  - platform: max44009
    name: "Light"
    mode: low_power
  - platform: bme280_i2c
    address: 0x76
    update_interval: 20s
    temperature:
      name: "Temperature"
    pressure:
      name: "Air pressure"
    humidity: 
      name: "Humidity"
    #iaq: 
    #  name: "IAQ"
    #co2_equivalent: 
    #  name: "CO2"
    #breath_voc_equivalent: 
    #  name: "Breath VOC Equivalent"
    
  - platform: internal_temperature
    name: 'Internal temperature'
  - platform: uptime
    name: Uptime S
  - platform: adc
    name: "Battery voltage"
    pin: GPIO0
    accuracy_decimals: 2
    update_interval: 10s
    attenuation: 12dB
    samples: 10
    filters:
      - multiply: 2.0
        
button:    
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: template
    name: "Prevent Sleep"
    on_press: 
      then:
        - deep_sleep.prevent: sleeper

light:
  - platform: status_led
    pin: GPIO15
    id: statusled

