esphome:
  name: esp32-c6-firebeetle
  friendly_name: esp32-c6-firebeetle

external_components:
  - source: github://pr#9021
    components: [adc]

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable Home Assistant API
api:
  encryption:
    key: "IyT8zQwmTGhLxHjIS9Om7tvxlIjlqo07Mgcbq0isYiU="

ota:
  - platform: esphome
    password: "1de71de3ffebf50ae3bd93fe1109b622"



# Enable logging
logger:
  level: VERBOSE
  

network:
  enable_ipv6: True

openthread:
  tlv: !secret openthread 
    
i2c:
  scl: GPIO20
  sda: GPIO19
  scan: True
  

text_sensor:
  - platform: version
    name: "Esphome Version"
  - platform: uptime
    name: Uptime
    format:
      separator: " "
      days: "d"
      hours: "h"
      minutes: "m"
  - platform: openthread_info
    ip_address:
      name: "Off-mesh routable IP Address"
    channel:
      name: "Channel"
    role:
      name: "Device Role"
      id: role
    rloc16:
      name: "RLOC16"
    ext_addr:
      name: "Extended Address"
    eui64:
      name: "EUI64 Interface ID"
    network_name:
      name: "Network Name"
    network_key:
      name: "Network Key"
    pan_id:
      name: "PAN ID"
    ext_pan_id:
      name: "Extended PAN ID"

#deep_sleep:
#  run_duration: 120s
#  sleep_duration: 5min
#  id: deep_sleep_1

globals:
  - id: allowsleep
    type: int
    restore_value: True
    initial_value: "0"


sensor:
  - platform: bme280_i2c
    temperature:
      name: "Temperature"
    pressure:
      name: "Air pressure"
    humidity:
      name: "Humidity"
  - platform: internal_temperature
    name: 'Internal temperature'
  - platform: uptime
    name: Uptime S
  - platform: adc
    name: "Battery voltage"
    pin: GPIO0
    accuracy_decimals: 2
    update_interval: 60s
    attenuation: 12dB
    samples: 10
    filters:
      - multiply: 2.0

button:    
  - platform: restart
    name: "Restart"
    entity_category: diagnostic 

status_led:
  pin: GPIO15

            
