esphome:
  name: espcamera

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "3d01a0bb3c2db3f521c6d0c493ba1773"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Espcamera Fallback Hotspot"
    password: "oWiaDq4n3oiB"

i2c:
  sda: 21
  scl: 22

# Comment out if you have a font file in place, otherwise it won't compile
font:
  - file: "fonts/Roboto/Roboto-Regular.ttf"
    id: roboto
    size: 14

display:
 - platform: ssd1306_i2c
   model: "SSD1306 128x64"
   rotation: 180
   lambda: |-
     it.print(0, 10, id(roboto), "Hello World!");
     
esp32_camera:
  name: Camera
  external_clock:
    pin: 32
    frequency: 20MHz
  i2c_pins:
    sda: 13
    scl: 12
  data_pins:
    - 5
    - 14
    - 4
    - 15
    - 18
    - 23
    - 36
    - 39
  vsync_pin: 27
  href_pin: 25
  pixel_clock_pin: 19
  resolution: 640x480 # Can be higher, I think, but this has a pretty good framerate

binary_sensor:
  - platform: gpio
    pin: 33
    name: "PIR Sensor"
    device_class: motion
  - platform: gpio
    pin: 
      number: 34
      inverted: true
    name: "Button"
