substitutions:
  room: gaestezimmer
  uroom: Gästezimmer


esphome:
  name: $room-sensor
  friendly_name: "$uroom"
  area: "$uroom"
                

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERBOSE
  

# Enable Home Assistant API
api:
  encryption:
    key: "GE0KcSEOHy/XjCR7/cd2kdDiO3rD3Vhs1ilWb5106rQ="

ota:
  - platform: esphome
    

network:
  enable_ipv6: True

openthread:
  tlv: !secret openthread 

debug:  

bluetooth_proxy:
  

i2c:
  sda: GPIO21
  scl: GPIO20
  scan: True
 
bme68x_bsec2_i2c:
  model: bme680
  address: 0x77
  temperature_offset: 3.0
  
text_sensor:
  - platform: bme68x_bsec2
    iaq_accuracy: 
      name: "IAQ Accuracy"
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

  - platform: version
    name: "Esphome Version"
  - platform: openthread_info
    ip_address:
      name: "Off-mesh routable IP Address"
    channel:
      name: "Channel"
    role:
      name: "Device Role"
      id: role
    rloc16:
      name: "RLOC16"
    ext_addr:
      name: "Extended Address"
    eui64:
      name: "EUI64 Interface ID"
    network_name:
      name: "Network Name"
    network_key:
      name: "Network Key"
    pan_id:
      name: "PAN ID"
    ext_pan_id:
      name: "Extended PAN ID"


sensor:
  - platform: tsl2561
    name: "Light"
  - platform: bme68x_bsec2
    temperature:
      name: "Temperatur"
    pressure:
      name: "Luftdruck"
    humidity:
      name: "Luftfeuchtigkeit"
    iaq: 
      name: "IAQ"
    co2_equivalent: 
      name: "CO2"
    breath_voc_equivalent: 
      name: "Breath VOC Equivalent"
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
    cpu_frequency:
      name: "CPU Frequency"

  - platform: internal_temperature
    name: 'Internal temperature'
  - platform: uptime
    name: Uptime
  
button:    
  - platform: restart
    name: "Restart"
    entity_category: diagnostic 
  - platform: safe_mode
    name: "Restart (Safe Mode)"

light:
  - platform: esp32_rmt_led_strip
    id: builtin_led
    rgb_order: RGB
    pin: GPIO8
    num_leds: 1
    #rmt_channel: 0
    chipset: ws2812
    name: "LED"

