
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
 
network:
  enable_ipv6: True

ota:
  password: "87de156915a18caa81c96ce93a4561e7"
  platform: esphome


# ---
substitutions:
  room: hausanschlussraum
  uroom: Hausanschlussraum

esphome:
  name: $room-sensor
  area: Hausanschlussraum
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led
      



# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
      
bluetooth_proxy:
  active: true

i2c:
  - id: bus_a
    scan: true
    sda: GPIO21
    scl: GPIO22


sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    address: 0x39
    update_interval: 60s
    accuracy_decimals: 2
  - platform: bme280_i2c
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -7
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    address: 0x76
    update_interval: 5s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  - platform: internal_temperature
    id: ${room}_internaltemp
    name: "${uroom} CPU Temperatur"

light:
  - platform: neopixelbus
    id: led
    variant: WS2811
    type: GRB
    pin: GPIO18
    num_leds: 1
    name: "${uroom} LED"

