
ota:
  password: "7d6fd9a0f0987ff03295ddf0a2e1a7c9"
  platform: esphome


esp8266:
  board: d1_mini
 # framework:
 #   version: 2.7.4

network:
  enable_ipv6: True

# ---
substitutions:
  room: "heizraum"
  uroom: "Heizraum"

esphome:
  name: $room-sensor
  area: Heizraum
  on_boot:
    priority: 600
    then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led
      
            

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "Fz8wHY3oM2k15FqdYad80/YR2bsDcy2qMQVLwNYX2Hs="

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 192.168.24.113


i2c:
  - id: bus_a
    scan: true
    sda: 4
    scl: 5
#    frequency: 400kHz

bme680_bsec:
  address: 0x77
  temperature_offset: -1.0
#  sample_rate: ULP

sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    address: 0x39
    accuracy_decimals: 2
  - platform: bme680_bsec
    temperature:
      accuracy_decimals: 2
      name: "${uroom} Temperatur"
      id: ${room}_temperature
    pressure:
      accuracy_decimals: 2
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
    humidity:
      accuracy_decimals: 2
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
    gas_resistance:
      accuracy_decimals: 2
      name: "${uroom} Gas Resistance"
    iaq:
      accuracy_decimals: 2
      name: "${uroom} IAQ"
    co2_equivalent:
      accuracy_decimals: 2
      name: "${uroom} CO2 Equivalent"
      id: ${room}_co2
    breath_voc_equivalent:
      accuracy_decimals: 2
      name: "${uroom} Breath VOC Equivalent"
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  
text_sensor:
  - platform: bme680_bsec
    iaq_accuracy:
      name: "${uroom} IAQ Accuracy"
      
light:
  - platform: neopixelbus
    id: led
    variant: WS2811
    type: GRB
    pin: 14
    num_leds: 1
    name: "${uroom} LED"
