esphome:
  name: heltec-esp32-lora-01
  friendly_name: heltec-esp32-lora-01

esp32:
  board: esp32-s3-devkitc-1
  # board: heltec_wireless_stick_lite
  framework:
    type: esp-idf
    

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "Zsfj/0ckYOdH4dcIlzMPiPVfTfymPUBORf2GLnmNxdQ="

ota:
  password: "75cc8c3555a1ed90078f23ca5a3a5554"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

bluetooth_proxy:
  active: true

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"

sensor:
  - platform: wifi_signal
    name: "WiFi Signal Sensor"

