esphome:
  name: ledstreifen

esp8266:
  board: d1_mini

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
  password: "47ebdbce69201d53c8c26bba603d0cd2"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails


wled:
  
light:
  - platform: neopixelbus
    type: GRB
    variant: WS2811
    pin: GPIO03
    num_leds: 200
    name: "NeoPixel"
    effects:
      - wled:
          port: 21324
 