substitutions:
  room: loggia
  uroom: 2OG-Loggia
  rssi_present: id(harssi_present).state
  rssi_not_present: id(harssi_not_present).state

external_components:
#  - source: github://berfenger/esphome_components
#    components: [ max44009 ]
#  - source: github://pr#5366
#    components: [as3935_i2c]

esphome:
  name: ${room}-sensor
  area: Loggia

esp8266:
  board: d1_mini

# Enable logging
logger:
  baud_rate: 0
  
uart:
  tx_pin: GPIO1
  rx_pin: GPIO3
  baud_rate: 9600
  

# Enable Home Assistant API
api:

ota:
  password: "3a7aa5e7e9fdcb0e7865837a88284d08"
  safe_mode: true

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart (Normal Mode)"
    
mqtt:
  broker: mqtt.ch5.garf.de
  discovery: false
  discovery_retain: false
  topic_prefix: /Chattenweg5/$uroom/sensor
  reboot_timeout: 0s
  keepalive: 20s
  username: $room-sensor
  password: $room-sensor
  
i2c:
  - id: bus_a
    scan: true
    # frequency: 10khz
    sda: 4
    scl: 5
    
#as3935_i2c:
#  irq_pin: 13
#  capacitance: 12
#  indoor: false
#  address: 0x03
#  setup_priority: -200
  # spike_rejection: 6
  # indoor: false

#binary_sensor:
#  - platform: as3935
#    name: "Storm Alert"

sensor:
  - platform: hydreon_rgxx
    model: "RG_15"
    update_interval: 60s
    acc:
      name: "Rain"
    event_acc:
      name: "Rain Event"
    total_acc:
      name: "Rain Total"
    r_int:
      name: "Rain Intensity"
 
#  - platform: as3935
#    lightning_energy:
#      name: "Lightning Energy"
#    distance:
#      name: "Distance Storm"

  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -5
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/$uroom/temperature"
              payload: !lambda |-
                return to_string(id(${room}_temperature).state);
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/$uroom/airpressure"
              payload: !lambda |-
                return to_string(id(${room}_pressure).state);
    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
      on_value:
        then:
          - mqtt.publish:
              topic: "/Chattenweg5/$uroom/humidity"
              payload: !lambda |-
                return to_string(id(${room}_humidity).state);
    address: 0x76
    
  - platform: max44009
    name: "${uroom} Helligkeit"
    id: "${room}_light"
    accuracy_decimals: 2
    on_value:
      then:
        - mqtt.publish:
            topic: "/Chattenweg5/$uroom/light"
            payload: !lambda |-
              return to_string(id(${room}_light).state);
    update_interval: 60s

  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
