# external_components:
#  - source: github://pr#4847
#    components: [ ld2420 ]
#    refresh: 0s

substitutions:
  room: og1flur
  uroom: 1OG-Flur

esphome:
  name: $room-sensor
  friendly_name: $uroom
  area: Treppenhaus
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"


  on_boot:
#    - priority: 250
#      then:
#        - delay: 15s
#        - lambda: |-
#            id(ble_tracker).set_scan_continuous(true);
#            id(ble_tracker).start_scan();
    - priority: 600
      then:
      - switch.turn_on: display_on
      - display.page.show: empty
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led
      - display.page.show: running

      
esp32:
  board: adafruit_feather_esp32s3
  # board: lolin_s3_mini
  variant: esp32s3
  framework:
    type: arduino
    # type: esp-idf
    # version: recommended
    # platform_version: 6.2.0




# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "diWWHcmRsJ/LUUIbmHmYBbdKCIjlCqYAYwPwG4VeOSA="

ota:
  password: "cc96ae441bb9818abd445b2748e2a14b"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

network:
  enable_ipv6: True

# esp32_ble_tracker:
#  id: ble_tracker
#  scan_parameters:
#    continuous: false
#    interval: 211ms
#    window: 120ms
#    active: true

#bluetooth_proxy:
#  active: true

i2c:
  - id: bus_a
    scan: True
    sda: GPIO35
    scl: GPIO36

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO16
  rx_pin: GPIO18

# network:
#  enable_ipv6: true

ld2410:

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
      still_threshold:
        name: g0 still threshold
    g1:
      move_threshold:
        name: g1 move threshold
      still_threshold:
        name: g1 still threshold
    g2:
      move_threshold:
        name: g2 move threshold
      still_threshold:
        name: g2 still threshold
    g3:
      move_threshold:
        name: g3 move threshold
      still_threshold:
        name: g3 still threshold
    g4:
      move_threshold:
        name: g4 move threshold
      still_threshold:
        name: g4 still threshold
    g5:
      move_threshold:
        name: g5 move threshold
      still_threshold:
        name: g5 still threshold
    g6:
      move_threshold:
        name: g6 move threshold
      still_threshold:
        name: g6 still threshold
    g7:
      move_threshold:
        name: g7 move threshold
      still_threshold:
        name: g7 still threshold
    g8:
      move_threshold:
        name: g8 move threshold
      still_threshold:
        name: g8 still threshold

select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "LD2410 baud rate"
    light_function:
      name: "light function"
    out_pin_level:
      name: "out pin level"

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"
  - platform: ld2410
    factory_reset:
      name: "factory reset"
    restart:
      name: "LD2410 restart"
    query_params:
      name: "query params"

switch:
  - platform: template
    id: display_on
    optimistic: true
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"

light:
  - platform: neopixelbus
    pin: GPIO47
    variant: ws2811
    num_leds: 1
    name: LED
    type: RGB
    id: led
#  - platform: fastled_clockless
#    chipset: WS2811
#    pin: GPIO47
#    num_leds: 1
#    rgb_order: RGB
#    name: LED
#    id: led

# debug:

time:
  - platform: homeassistant
    id: homeassistant_time
    on_time:
      - seconds: 0
        minutes: 0
        hours: 22
        then:
          - switch.turn_off: display_on
      - seconds: 0
        minutes: 0
        hours: 7
        then:
          - switch.turn_on: display_on
          
font:
  - file: "fonts/Atkinson/AtkinsonHyperlegible-Regular.ttf"
    # file: "fonts/B612/B612-Bold.ttf"
    # file: "fonts/Roboto/DroidSans-Bold.ttf"
    id: roboto
    size: 12
 
display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    rotation: 180
    pages:
      - id: empty
        lambda: |-
          it.fill(COLOR_OFF);
      - id: running
        lambda: |-
          if (id(display_on).state) {
            int fensterOffen = 0;
            int stretchFactor=18;
            if (id(bad1_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Bad1");
              fensterOffen++;
            }
            if (id(bad2_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Bad2");
              fensterOffen++;
            }
            if (id(kueche_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Küche");
              fensterOffen++;
            }
            if (id(gaestezimmer_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Gaestezimmer");
              fensterOffen++;
            }
            if (id(schlafzimmer_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Schlafzimmer");
              fensterOffen++;
            }
            if (id(wohnzimmer_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Wohnzimmer");
              fensterOffen++;
            }
            if (id(arbeitszimmer_fenster).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Arbeitszimmer");
              fensterOffen++;
            }
            if (id(haustuer).state) {
              it.printf(0,stretchFactor*fensterOffen,id(roboto),"Haustuer");
              fensterOffen++;
            }
            
          } else
            it.fill(COLOR_OFF);

text_sensor:
#  - platform: debug
#    device:
#      name: "Device Info"
#    reset_reason:
#      name: "Reset Reason"
  - platform: homeassistant
    internal: true
    id: wostehtdasAuto
    entity_id: input_text.carlocation
  - platform: ld2410
    version:
      name: "LD2410 firmware version"
    mac_address:
      name: "LD2410 mac address"

sensor:
#  - platform: debug
#    free:
#      name: "Heap Free"
#    block:
#      name: "Heap Max Block"
#    loop_time:
#      name: "Loop Time"
  - platform: homeassistant
    entity_id: sensor.garten_temperatur
    id: garten_temperatur
  - platform: homeassistant
    entity_id: sensor.vorgarten_temperatur
    id: vorgarten_temperatur  
  - platform: homeassistant
    entity_id: sensor.2og_loggia_temperatur
    id: loggia_temperatur
  - platform: bme680
    i2c_id: bus_a
    address: 0x77
    temperature:
      name: "Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -5
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    pressure:
      name: "Luftdruck"
      id: ${room}_pressure
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      accuracy_decimals: 2
      id: ${room}_humidity
      name: "Luftfeuchtigkeit"
    gas_resistance:
      name: "Gas"
      id: ${room}_gas
      accuracy_decimals: 2
    update_interval: 5s
  
  - platform: template
    name: "IAQ"
    id: ${room}_iaq
    unit_of_measurement: IAQ
    lambda: 'return log(id(${room}_gas).state) + 0.04 * id(${room}_humidity).state;' 

  - platform: max44009
    name: "Light"
    id: ${room}_light
    update_interval: 60s
    unit_of_measurement: "lx"
  - platform: ld2410
    moving_distance:
      name : "Moving Distance"
      id: ${room}_moving_distance
    still_distance:
      name: "Still Distance"
      id: ${room}_still_distance
    moving_energy:
      name: "Move Energy"
      id: ${room}_move_energy
    still_energy:
      name: Still Energy
      id: ${room}_still_energy
    detection_distance:
      name: "Detection Distance"
      id: ${room}_detection_distance
    light:
      name: LD2410 Light
    g0:
      move_energy:
        name: "g0 move energy"
      still_energy:
        name: "g0 still energy"
    g1:
      move_energy:
        name: "g1 move energy"
      still_energy:
        name: "g1 still energy"
    g2:
      move_energy:
        name: "g2 move energy"
      still_energy:
        name: "g2 still energy"
    g3:
      move_energy:
        name: "g3 move energy"
      still_energy:
        name: "g3 still energy"
    g4:
      move_energy:
        name: "g4 move energy"
      still_energy:
        name: "g4 still energy"
    g5:
      move_energy:
        name: "g5 move energy"
      still_energy:
        name: "g5 still energy"
    g6:
      move_energy:
        name: "g6 move energy"
      still_energy:
        name: "g6 still energy"
    g7:
      move_energy:
        name: "g7 move energy"
      still_energy:
        name: "g7 still energy"
    g8:
      move_energy:
        name: "g8 move energy"
      still_energy:
        name: "g8 still energy"

binary_sensor:
  - platform: ld2410
    has_target:
      name: "Presence"
      filters:
      - delayed_off: 60s
    has_moving_target:
      id: presence
      name: "Moving Target"
      device_class: motion
      filters:
        - delayed_on: 1s
      on_press:
        then:
          - if:
              condition:
                binary_sensor.is_on: alarmierung
              then:
                - light.turn_on:
                    id: led
                    brightness: 100%
                    red: 100%
                    green: 0
                    blue: 0
      on_release:
        then:
          - light.turn_off: led 
    has_still_target:
      name: "Still Target"
    out_pin_presence_status:
      name: out pin presence status
  - platform: homeassistant
    entity_id: input_boolean.alarmierung
    id: alarmierung
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_bad1_state
    id: bad1_fenster
    name: "Bad1"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_bad2_state
    id: bad2_fenster
    name: "Bad2"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_gaestezimmer_35fd906b_ias_zone
    id: gaestezimmer_fenster
    name: "Gaestezimmer"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_kueche_state
    id: kueche_fenster
    name: "Küche"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_schlafzimmer_state
    id: schlafzimmer_fenster
    name: "Schlafzimmer"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.fenster_wohnzimmer_state
    id: wohnzimmer_fenster
    name: "Wohnzimmer"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.balkontuer_arbeitszimmer_state
    id: arbeitszimmer_fenster
    name: "Arbeitszimmer"
    internal: true
  - platform: homeassistant
    entity_id: binary_sensor.shellydw2_18db68_door
    id: haustuer
    name: "Haustür"
    internal: true
    on_state:
      then:
        - light.turn_off: led
  - platform: homeassistant
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_0e3dcf03_on_off
    id: briefkasten
    name: "Briefkasten"
    internal: true
    on_press:
      then:
        - light.turn_on:
            id: led
            brightness: 80%
            red: 100%
            green: 0
            blue: 0
    on_release:
      then:
        - light.turn_on:
            id: led
            brightness: 80%
            red: 1
            green: 1
            blue: 0