
# ---
substitutions:
  room: schlafzimmer
  uroom: Schlafzimmer

esphome:
  name: $room-sensor
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
  on_boot:
    - priority: 250
      then:
        - delay: 15s
        - lambda: |-
            id(ble_tracker).set_scan_continuous(true);
            id(ble_tracker).start_scan();

esp32:
  board: lolin_c3_mini
  framework:
    type: arduino

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    continuous: false
    interval: 211ms
    window: 120ms
    active: true

bluetooth_proxy:
  active: true

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "9lQR30PDX+wuGtH3tSs5+Vud4RQNHkXGYCZFZz7/7hk="

ota:
  password: "c2df0cc4f72314d60ce5db3c84c8d1bd"

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: true
  output_power: 10
  

i2c:
  - id: bus_a
    scan: true
    sda: GPIO8
    scl: GPIO10
    frequency: 10khz

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO6
  rx_pin: GPIO7

ld2410:
  timeout: 150s
  max_move_distance : 4.5m
  max_still_distance: 2.25m
  g0_move_threshold: 50
  g1_move_threshold: 50
  g2_move_threshold: 40
  g3_move_threshold: 40
  g4_move_threshold: 40
  g5_move_threshold: 40
  g6_move_threshold: 30
  g7_move_threshold: 30
  g8_move_threshold: 30
  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 40
  g3_still_threshold: 40
  g4_still_threshold: 40
  g5_still_threshold: 40
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15

sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    accuracy_decimals: 2
    address: 0x39
  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -5
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2

    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
    
    gas_resistance:
      name: "${uroom} Gas"
      id: ${room}_gas
      accuracy_decimals: 2
    
    address: 0x77
    update_interval: 30s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  - platform: template
    name: "${uroom} IAQ"
    id: ${room}_iaq
    unit_of_measurement: IAQ
    lambda: 'return log(id(${room}_gas).state) + 0.04 * id(${room}_humidity).state;' 

  - platform: ld2410
    moving_distance:
      name : "${uroom} Moving Distance"
      id: ${room}_moving_distance
    still_distance:
      name: "${uroom} Still Distance"
      id: ${room}_still_distance
    moving_energy:
      name: "${uroom} Move Energy"
      id: ${room}_move_energy
    still_energy:
      name: Still Energy
      id: ${room}_still_energy
    detection_distance:
      name: "${uroom} Detection Distance"
      id: ${room}_detection_distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: "${uroom} Presence"
    has_moving_target:
      id: presence
      name: "${uroom} Moving Target"
      device_class: motion
      filters:
        - delayed_on: 1s
    has_still_target:
      name: "${uroom} Still Target"
  - platform: homeassistant
    entity_id: input_boolean.alarmierung
    id: alarmierung
    internal: true