
# ---
substitutions:
  room: schlafzimmer
  uroom: Schlafzimmer

esphome:
  name: $room-sensor
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino


# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:
  encryption:
    key: "9lQR30PDX+wuGtH3tSs5+Vud4RQNHkXGYCZFZz7/7hk="

ota:
  password: "c2df0cc4f72314d60ce5db3c84c8d1bd"

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: true
  

i2c:
  - id: bus_a
    scan: true
    sda: GPIO33
    scl: GPIO35

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO16
  rx_pin: GPIO18


sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    accuracy_decimals: 2
    address: 0x39
  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -5
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2

    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
    
    gas_resistance:
      name: "${uroom} Gas"
      id: ${room}_gas
      accuracy_decimals: 2
    
    address: 0x77
    update_interval: 30s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  - platform: template
    name: "${uroom} IAQ"
    id: ${room}_iaq
    unit_of_measurement: IAQ
    lambda: 'return log(id(${room}_gas).state) + 0.04 * id(${room}_humidity).state;' 
