
esp8266:
  board: d1_mini


ota:
  password: "da849b2cb540251bf7f9ae5d91b6350f"

# ---
substitutions:
  room: schlafzimmer
  uroom: Schlafzimmer

esphome:
  name: $room-sensor



# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:


button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: true
  

i2c:
  - id: bus_a
    scan: true
    sda: 4
    scl: 5


sensor:
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    accuracy_decimals: 2
    address: 0x39
  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -5
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2

    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2

    address: 0x76
    update_interval: 30s

