substitutions:
  room: stromzaehler
  uroom: Stromzähler


# Enable logging
logger:
  level: INFO
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "PX6dzBe3mYBrVwX7/7wdgGXGeRhe/hK+Gy7qbGLOyAc="

ota:
  password: "39a17ba51ea3d5f47e908f6d7a2f00a0"


esphome:
  name: stromzaehler
  area: Hausanschlussraum

esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino
 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: true
  
uart:
  rx_pin:
    number: GPIO27
    mode:
     input: true
     pullup: true
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
  # debug:
  #  direction: rx
  #  after:
  #    timeout: 1s


sml:
  id: mysml

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"

sensor:
  - platform: wifi_signal
    name: "$uroom WiFi Signal"
    id: wifi_rssi
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 1
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "Current power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    on_value:
      then:
        - switch.turn_on: blueled
  - platform: internal_temperature
    id: ${room}_internaltemp
    name: "${uroom} CPU Temperatur"

switch:
  - platform: gpio
    pin: GPIO2
    id: blueled
    internal: true
    name: "$uroom Status LED"
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: blueled
