substitutions:
  room: stromzaehler
  uroom: Stromzähler


# Enable logging
logger:
  level: ERROR
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "PX6dzBe3mYBrVwX7/7wdgGXGeRhe/hK+Gy7qbGLOyAc="

ota:
  password: "39a17ba51ea3d5f47e908f6d7a2f00a0"
  platform: esphome


esphome:
  name: stromzaehler
  area: Hausanschlussraum

esp32:
  board: wemos_d1_mini32
  framework:
    type: esp-idf
    

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 5min
  fast_connect: true
  
#network:
#  enable_ipv6: True

uart:
  rx_pin:
    number: GPIO27
    mode:
     input: true
     pullup: true
  baud_rate: 9600
  data_bits: 8
  stop_bits: 1
#  debug:
#    direction: rx
#    after:
#      timeout: 1s


sml:
  id: mysml

output:
  - platform: gpio
    pin: 
      number: GPIO32
      mode:
        pullup: True
        output: true
    id: senderled
    inverted: true

button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"
  - platform: restart
    name: "$uroom Restart"
  - platform: template
    name: "Output LED"
    id: outputled
    on_press:
      then:
        - output.turn_on: senderled
        - delay: 1000ms
        - output.turn_off: senderled
  - platform: template
    name: "Output LED 5s"
    on_press:
      then:
        - output.turn_on: senderled
        - delay: 6000ms
        - output.turn_off: senderled
        



sensor:
  - platform: wifi_signal
    name: "$uroom WiFi Signal"
    id: wifi_rssi
  - platform: sml
    name: "Total energy"
    sml_id: mysml
    obis_code: "1-0:1.8.0"
    unit_of_measurement: kWh
    accuracy_decimals: 5
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.0001
  - platform: sml
    name: "Current power"
    sml_id: mysml
    obis_code: "1-0:16.7.0"
    unit_of_measurement: W
    device_class: power
    state_class: measurement
    on_value:
      then:
        - switch.turn_on: blueled
 
  - platform: internal_temperature
    id: ${room}_internaltemp
    name: "${uroom} CPU Temperatur"

switch:
  - platform: gpio
    pin: GPIO2
    id: blueled
    internal: true
    name: "$uroom Status LED"
    restore_mode: ALWAYS_OFF
    on_turn_on:
    - delay: 100ms
    - switch.turn_off: blueled

text_sensor:
  - platform: sml
    name: "Meter ID"
    sml_id: mysml
    obis_code: "1-0:96.1.0"
    format: uint
  - platform: sml
    name: "Manufacturer"
    sml_id: mysml
    obis_code: "1-0:96.50.1"
  
