esphome:
  name: wemos-s2-mini-test
  friendly_name: wemos-s2-mini-test
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino

# network:
#  enable_ipv6: true

# Enable logging
logger:
  level: debug

# Enable Home Assistant API
api:
  encryption:
    key: "9lQR30PDX+wuGtH3tSs5+Vud4RQNHkXGYCZFZz7/7hk="

ota:
  password: "c2df0cc4f72314d60ce5db3c84c8d1bd"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


i2c:
  - id: bus_a
    scan: True
    sda: GPIO33
    scl: GPIO35

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO16
  rx_pin: GPIO18

#light:
#  - platform: neopixelbus
#    pin: GPIO7
#    variant: ws2812
#    num_leds: 1
#    name: LED
#    id: led
#    type: GRB

debug:
  update_interval: 120s

ld2410:
  timeout: 150s
  max_move_distance : 6m
  max_still_distance: 0.75m
  g0_move_threshold: 50
  g1_move_threshold: 50
  g2_move_threshold: 40
  g3_move_threshold: 40
  g4_move_threshold: 40
  g5_move_threshold: 40
  g6_move_threshold: 30
  g7_move_threshold: 30
  g8_move_threshold: 30
  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 40
  g3_still_threshold: 40
  g4_still_threshold: 40
  g5_still_threshold: 40
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: max44009
    name: "Helligkeit"

  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "Temperatur"
      accuracy_decimals: 2
      filters:
        - offset: -1
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    pressure:
      name: "Luftdruck"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      name: "Luftfeuchtigkeit"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    gas_resistance:
      name: "Gas"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    address: 0x77
    update_interval: 5s

  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
