
esphome:
  name: wemos-s3-pro-test
  friendly_name: wemos-s3-pro-test

  on_boot:
    - priority: 600
      then:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 0
          blue: 0
      - wait_until:
          wifi.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 100%
          green: 100%
          blue: 0
      - wait_until:
          api.connected:
      - light.turn_on:
          id: led
          brightness: 100%
          red: 0%
          green: 100%
          blue: 0
      - delay: 1s
      - light.turn_off: led

esp32:
  board: lolin_s3
  framework:
    type: arduino

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: "sQSDyyXz/KSstdzM9CFNJk2RgYE8v2+JyigPOMYu0zo="

ota:
  password: "106d5aa8bbe1f6547717126203d12b22"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails

i2c:
  - id: bus_a
    scan: True
    sda: GPIO9
    scl: GPIO10



font:
  - file: "fonts/Roboto/DroidSans-Bold.ttf"
    id: roboto
    size: 14
  - file: "fonts/Roboto/DroidSans-Bold.ttf"
    id: headline
    size: 30
  - file: "fonts/Roboto/Roboto-Thin.ttf"
    id: thin
    size: 12

time:
  - platform: homeassistant
    id: esptime

image:
  - file: mdi:window-open-variant
    id: icon_openWindow
    resize: 40x40
  - file: mdi:window-closed-variant
    id: icon_closedWindow
    resize: 40x40
  - file: mdi:car-side
    id: icon_car
    resize: 40x40
  - file: mdi:arrow-left-bold
    id: icon_arrowleft
    resize: 40x40
  - file: mdi:arrow-right-bold
    id: icon_arrowright
    resize: 40x40
  # Temperature Icons
  - file: mdi:thermometer-high
    id: icon_thermometer_high
    resize: 80x80
  - file: mdi:thermometer-low
    id: icon_thermometer_low
    resize: 80x80
  - file: mdi:thermometer
    id: icon_thermometer_mid
    resize: 80x80
  - file: mdi:snowflake-thermometer
    id: icon_thermometer_snow
    resize: 80x80
  - file: mdi:sun-thermometer
    id: icon_thermometer_sun
    resize: 80x80

  

qr_code:
  - id: garf
    value: https://outpost.garf.de

spi:
  clk_pin: GPIO12
  # miso_pin: GPIO
  mosi_pin: GPIO11

display:
  - platform: waveshare_epaper
    id: epaper
    cs_pin: GPIO17
    dc_pin: GPIO16
    reset_pin: GPIO15
    busy_pin: GPIO18
    reset_duration: 2ms
    model: 7.50inv2
    update_interval: 60s
    rotation: 0
    lambda: |-
      int line=0;
      int x,y,frame;
      auto white = Color(255,255,255);
      auto black = Color(0,0,0);
      
      it.strftime(it.get_width(),0,id(thin),TextAlign::TOP_RIGHT,"%H:%M:%S",id(esptime).now());
      line=13;
      
      it.horizontal_line(0,line,it.get_width());
      
      line+=2;
      it.print(20,line,id(roboto),"Vorg.:");
      it.printf(it.get_width(),line,id(roboto),TextAlign::TOP_RIGHT,"%.1fC",id(vorgarten_temperatur).state);
      
      line+=16;
      // it.image(0,line,id(icon_thermometer));
      it.print(20,line,id(roboto),"Garten:");
      it.printf(it.get_width(),line,id(roboto),TextAlign::TOP_RIGHT,"%.1fC",id(garten_temperatur).state);
      
      line+=16;
      it.print(20,line,id(roboto),"Loggia:");
      it.printf(it.get_width(),line,id(roboto),TextAlign::TOP_RIGHT,"%.1fC",id(loggia_temperatur).state);
      
      line += 18;
      it.horizontal_line(0,line,it.get_width());

      line += 8;
      it.qr_code(0,line,id(garf),white,4);
      
      
      //------------------------------------------------------------------
      // Widget where is my car?
      // x,y,frame
      // size 82x40
      x = 0;
      y = it.get_height()-42;
      it.start_clipping(x,y,x+82,y+40)
      frame = 1;
      if (id(wostehtdasAuto).state.c_str()[0] == '<') {
        it.image(x,y,id(icon_arrowleft));
        it.image(x+40,y,id(icon_car));
      } else if (id(wostehtdasAuto).state.c_str()[0] == '>') {
        it.image(x,y,id(icon_car));
        it.image(x+40,y,id(icon_arrowright));
      } else {
        it.image(x+40,y,id(icon_car));
      }
      if (frame) {
        it.rectangle(x,y,82,40);
      }
      it.end_clipping();
      //------------------------------------------------------------------

      //------------------------------------------------------------------
      // Widget: QR code of guest network
      //------------------------------------------------------------------
      //------------------------------------------------------------------
      // Widget: Loggia Temperature
      // x,y,frame,thisid,headline
      // size
      //------------------------------------------------------------------
      x = 200;
      y = 200;
      frame = 1;
      auto thisid = id(loggia_temperatur);
      auto headline = "Loggia";
      
      if (frame) {
        it.rectangle(x,y,200,200);
      }
      it.print(x+2,y+2,id(headline),headline);
      auto thisicon;
      if (thisid.state <= 0)
        thisicon = id(icon_thermometer_snow);
      else if (thisid.state <= 10)
        thisicon = id(icon_thermometer_low);
      else if (thisid.state <= 25)
        thisicon = id(icon_thermometer_mid);
      else if (thisid.state <= 30)
        thisicon = id(icon_thermometer_high);
      else
        thisicon = id(icon_thermometer_sun);







button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"

light:
  - platform: neopixelbus
    pin: GPIO38
    variant: ws2811
    num_leds: 1
    name: LED
    type: RGB
    id: led

# interval:
#  - interval: 20s
#    then:
#      - component.update: epaper

sensor:
#  - platform: debug
#    free:
#      name: "Heap Free"
#    block:
#      name: "Heap Max Block"
#    loop_time:
#      name: "Loop Time"
  - platform: wifi_signal
    name: "WiFi Signal Sensor"
    id: wifi_rssi
  - platform: homeassistant
    entity_id: sensor.garten_temperatur
    id: garten_temperatur
  - platform: homeassistant
    entity_id: sensor.vorgarten_temperatur
    id: vorgarten_temperatur  
  - platform: homeassistant
    entity_id: sensor.2og_loggia_temperatur
    id: loggia_temperatur

text_sensor:
#  - platform: debug
#    device:
#      name: "Device Info"
#    reset_reason:
#      name: "Reset Reason"
  - platform: homeassistant
    internal: true
    id: wostehtdasAuto
    entity_id: input_text.carlocation

binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.lumi_lumi_sensor_magnet_aq2_0e3dcf03_on_off
    id: briefkasten
    name: "Briefkasten"
    internal: true
    on_press:
      then:
        - light.turn_on:
            id: led
            brightness: 80%
            red: 100%
            green: 0
            blue: 0
    on_release:
      then:
        - light.turn_on:
            id: led
            brightness: 80%
            red: 1
            green: 1
            blue: 0