
esphome:
  name: wemos-c3-mini-test
  friendly_name: wemos-c3-mini-test
  platformio_options: 
    board_build.extra_flags:
      - "-DARDUINO_USB_CDC_ON_BOOT=0"
  on_boot:
    - priority: 250
      then:
        - delay: 15s
        - lambda: |-
            id(ble_tracker).set_scan_continuous(true);
            id(ble_tracker).start_scan();

 

esp32:
  # board: esp32-c3-devkitm-1
  board: lolin_c3_mini
  framework:
    type: arduino

esp32_ble_tracker:
  id: ble_tracker
  scan_parameters:
    continuous: false
    interval: 211ms
    window: 120ms

bluetooth_proxy:
  active: true

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "mcCClDV+7HiR1ZZDc+RVFRKqfyvrnnwHDmsO8NkEZ9E="

ota:
  password: "f3df06b7590d777566ef5f663a754dad"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  output_power: 8.5

i2c:
  - id: bus_a
    scan: True
    sda: GPIO8
    scl: GPIO10

uart:
  baud_rate: 256000
  parity: NONE
  stop_bits: 1
  tx_pin: GPIO6
  rx_pin: GPIO7

#light:
#  - platform: neopixelbus
#    pin: GPIO7
#    variant: ws2812
#    num_leds: 1
#    name: LED
#    id: led
#    type: GRB

debug:
  update_interval: 120s

ld2410:
  timeout: 150s
  max_move_distance : 6m
  max_still_distance: 0.75m
  g0_move_threshold: 50
  g1_move_threshold: 50
  g2_move_threshold: 40
  g3_move_threshold: 40
  g4_move_threshold: 40
  g5_move_threshold: 40
  g6_move_threshold: 30
  g7_move_threshold: 30
  g8_move_threshold: 30
  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 40
  g3_still_threshold: 40
  g4_still_threshold: 40
  g5_still_threshold: 40
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15

font:
  - file: "fonts/Roboto/DroidSans-Bold.ttf"
    id: roboto
    size: 28
  - file: "fonts/Roboto/Roboto-Thin.ttf"
    id: smallfont
    size: 10

display:
  - platform: ssd1306_i2c
    model: "SH1106 128x64"
    address: 0x3C
    rotation: 0

text_sensor:
  - platform: debug
    device:
      name: "Device Info"
    reset_reason:
      name: "Reset Reason"
  - platform: wifi_info
    ip_address:
      name: ESP IP Address
      id: my_ip
    ssid:
      name: ESP Connected SSID
    bssid:
      name: ESP Connected BSSID
    mac_address:
      name: ESP Mac Wifi Address
    scan_results:
      name: ESP Latest Scan Results

button:
  - platform: safe_mode
    name: "Restart (Safe Mode)"
  - platform: restart
    name: "Restart"

sensor:
  - platform: debug
    free:
      name: "Heap Free"
    block:
      name: "Heap Max Block"
    loop_time:
      name: "Loop Time"
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s

  - platform: max44009
    name: "Helligkeit"

  - platform: bme680
    i2c_id: bus_a
    temperature:
      name: "Temperatur"
      accuracy_decimals: 2
      filters:
        - offset: -1
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    pressure:
      name: "Luftdruck"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    humidity:
      name: "Luftfeuchtigkeit"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    gas_resistance:
      name: "Gas"
      accuracy_decimals: 2
      filters:
        - sliding_window_moving_average:
            window_size: 10
            send_every: 6
    address: 0x77
    update_interval: 5s

  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target
