substitutions:
  room: wohnzimmer
  uroom: Wohnzimmer
  rssi_present: id(harssi_present).state
  rssi_not_present: id(harssi_not_present).state

esphome:
  name: $room-sensor
  on_boot:
    priority: 600
    then:
      - light.turn_off:
          id: ${room}_led


esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

status_led:
  pin: GPIO2

# Enable logging
logger:
  level: ERROR

# Enable Home Assistant API
api:

ota:
  password: "4e7af41530d582d1dec516dd1d216aed"
  safe_mode: true
  
button:
  - platform: safe_mode
    name: "$uroom Restart (Safe Mode)"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  # use_address: 192.168.24.143

bluetooth_proxy:
  active: true
  


i2c:
  - id: bus_a
    scan: true
    sda: 21
    scl: 22

binary_sensor:
  - platform: homeassistant
    entity_id: input_boolean.alarmierung
    id: alarmierung
    internal: true
  - platform: gpio
    pin: GPIO19
    id: ${room}_motion
    name: "${uroom} Motion"
    device_class: motion
    filters:
      - delayed_off: 60s
    on_press:
      then:
        - if:
            condition:
              binary_sensor.is_on: alarmierung
            then:
              - light.turn_on:
                  id: ${room}_led
                  brightness: 100%
                  red: 100%
                  green: 0
                  blue: 0
    on_release:
      then:
        - light.turn_off: ${room}_led
  

sensor:
          
  - platform: homeassistant
    name: HA RSSI Present Value
    entity_id: input_number.rssi_present  #insert your input.number entity id here
    id: harssi_present
  - platform: homeassistant
    name: HA RSSI Not Present Value
    entity_id: input_number.rssi_not_present  #insert your input.number entity id here
    id: harssi_not_present
  - platform: wifi_signal
    name: "${uroom} WiFi Signal"
    update_interval: 60s
  - platform: tsl2561
    i2c_id: bus_a
    id: ${room}_light
    name: "${uroom} Light"
    address: 0x39
    update_interval: 60s
    accuracy_decimals: 2
  - platform: bme280
    i2c_id: bus_a
    temperature:
      name: "${uroom} Temperatur"
      id: ${room}_temperature
      accuracy_decimals: 2
      filters:
        - offset: -1.3
    pressure:
      name: "${uroom} Luftdruck"
      id: "${room}_pressure"
      accuracy_decimals: 2
    humidity:
      name: "${uroom} Luftfeuchtigkeit"
      id: "${room}_humidity"
      accuracy_decimals: 2
    address: 0x76
    update_interval: 60s
  - platform: absolute_humidity
    name: "${uroom} Absolute Luftfeuchtigkeit"
    temperature: ${room}_temperature
    humidity: ${room}_humidity
  - platform: internal_temperature
    id: ${room}_internaltemp
    name: "${uroom} CPU Temperatur"


light:
  - platform: neopixelbus
    type: RGB
    id: ${room}_led
    variant: WS2811
    pin: GPIO1
    num_leds: 1
    name: "${uroom} LED"
    

